connection_string: DefaultEndpointsProtocol=https;AccountName=ifcbwestus;AccountKey=bHLeaeVSCT4DK7nwzof/lTmKctp6+ljI9e95efaZTM8klc6MwMseApKN9qRT8GXFxwLnroDtvXGE+ASt14eASA==;EndpointSuffix=core.windows.net
image_container: exportsnp
server: ifcbserver.database.windows.net
database: ifcbsql
db_user: ifcbadmin
db_password: Phyt0plankton!
subscription_id: 91804dbe-1fd2-4384-8b66-2b5e4ad1f2f2
resource_group: UTOPIA
workspace_name: pivot
experiment_name: adt-pivot
api_key: 4B2DTMyhNHgIk3lJtt8MSdBU5QodpCNf
model_name: basemodel
endpoint_name: basemodel-endpoint
deployment_name: pivot-basemodel
